export const ApplicationStatus = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  MORE_INFO_REQUIRED: 'MORE_INFO_REQUIRED',
  VERIFIED: 'VERIFIED',
  APPROVED: 'APPROVED',
  WAITLISTED: 'WAITLISTED',
  ASSIGNED_TO_EVENT: 'ASSIGNED_TO_EVENT',
  PARTICIPATION_CONFIRMED: 'PARTICIPATION_CONFIRMED',
  PARTICIPATION_DECLINED: 'PARTICIPATION_DECLINED',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED',
  WITHDRAWN: 'WITHDRAWN',
  ARCHIVED: 'ARCHIVED',
} as const;

export const EventStatus = {
  DRAFT: 'DRAFT',
  PLANNING: 'PLANNING',
  OPEN_FOR_RIDERS: 'OPEN_FOR_RIDERS',
  FULL: 'FULL',
  CONFIRMED: 'CONFIRMED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  POSTPONED: 'POSTPONED',
} as const;

export const RsvpStatus = {
  INTERESTED: 'INTERESTED',
  CONFIRMED: 'CONFIRMED',
  WAITLISTED: 'WAITLISTED',
  CANCELLED: 'CANCELLED',
  CHECKED_IN: 'CHECKED_IN',
  NO_SHOW: 'NO_SHOW',
} as const;

export const ParticipationStatus = {
  ASSIGNED: 'ASSIGNED',
  INVITED: 'INVITED',
  PARENT_CONFIRMED: 'PARENT_CONFIRMED',
  PARENT_DECLINED: 'PARENT_DECLINED',
  ATTENDED: 'ATTENDED',
  CANCELLED: 'CANCELLED',
  NO_SHOW: 'NO_SHOW',
} as const;

export const FieldVisibility = {
  PRIVATE_STAFF: 'PRIVATE_STAFF',
  PARENT_VISIBLE: 'PARENT_VISIBLE',
  PARTICIPANT_VISIBLE: 'PARTICIPANT_VISIBLE',
  PUBLIC_SUMMARY: 'PUBLIC_SUMMARY',
} as const;

export const LocationVisibilityPolicy = {
  PUBLIC: 'PUBLIC',
  AFTER_RSVP: 'AFTER_RSVP',
  BEFORE_EVENT: 'BEFORE_EVENT',
  APPROVED_ONLY: 'APPROVED_ONLY',
} as const;
