export const PERMISSIONS = {
  TENANTS_MANAGE: 'tenants:manage',
  PLATFORM_USERS_MANAGE: 'platform:users:manage',
  USERS_MANAGE: 'users:manage',
  ROLES_MANAGE: 'roles:manage',
  REGIONS_MANAGE: 'regions:manage',
  SETTINGS_MANAGE: 'settings:manage',
  AUDIT_READ: 'audit:read',
  ANALYTICS_READ: 'analytics:read',
  MODERATION_MANAGE: 'moderation:manage',
  APPLICATIONS_CREATE: 'applications:create',
  APPLICATIONS_READ_OWN: 'applications:read_own',
  APPLICATIONS_REVIEW: 'applications:review',
  APPLICATIONS_ASSIGN: 'applications:assign',
  CHILD_PRIVATE_READ: 'child_private:read',
  EVENTS_CREATE: 'events:create',
  EVENTS_PUBLISH: 'events:publish',
  EVENTS_READ_PUBLIC: 'events:read_public',
  EVENTS_MANAGE: 'events:manage',
  RSVP_MANAGE_OWN: 'rsvp:manage_own',
  ATTENDANCE_RECORD: 'attendance:record',
  NOTIFICATIONS_CAMPAIGN: 'notifications:campaign',
  CONSENTS_MANAGE_OWN: 'consents:manage_own',
  MEDIA_MODERATE: 'media:moderate',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const TENANT_ROLES = {
  ADMIN: 'ADMIN',
  EVENT_MANAGER: 'EVENT_MANAGER',
  RIDER: 'RIDER',
  PARENT: 'PARENT',
} as const;

export type TenantRole = (typeof TENANT_ROLES)[keyof typeof TENANT_ROLES];

export const PLATFORM_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
} as const;

export type PlatformRole = (typeof PLATFORM_ROLES)[keyof typeof PLATFORM_ROLES];

export const ROLE_PERMISSIONS: Record<TenantRole, Permission[]> = {
  ADMIN: [
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.ROLES_MANAGE,
    PERMISSIONS.REGIONS_MANAGE,
    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.MODERATION_MANAGE,
    PERMISSIONS.APPLICATIONS_REVIEW,
    PERMISSIONS.APPLICATIONS_ASSIGN,
    PERMISSIONS.CHILD_PRIVATE_READ,
    PERMISSIONS.EVENTS_CREATE,
    PERMISSIONS.EVENTS_PUBLISH,
    PERMISSIONS.EVENTS_READ_PUBLIC,
    PERMISSIONS.EVENTS_MANAGE,
    PERMISSIONS.ATTENDANCE_RECORD,
    PERMISSIONS.NOTIFICATIONS_CAMPAIGN,
    PERMISSIONS.MEDIA_MODERATE,
  ],
  EVENT_MANAGER: [
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.APPLICATIONS_REVIEW,
    PERMISSIONS.APPLICATIONS_ASSIGN,
    PERMISSIONS.CHILD_PRIVATE_READ,
    PERMISSIONS.EVENTS_CREATE,
    PERMISSIONS.EVENTS_PUBLISH,
    PERMISSIONS.EVENTS_READ_PUBLIC,
    PERMISSIONS.EVENTS_MANAGE,
    PERMISSIONS.ATTENDANCE_RECORD,
    PERMISSIONS.NOTIFICATIONS_CAMPAIGN,
    PERMISSIONS.MEDIA_MODERATE,
  ],
  RIDER: [
    PERMISSIONS.APPLICATIONS_CREATE,
    PERMISSIONS.APPLICATIONS_READ_OWN,
    PERMISSIONS.EVENTS_READ_PUBLIC,
    PERMISSIONS.RSVP_MANAGE_OWN,
    PERMISSIONS.CONSENTS_MANAGE_OWN,
  ],
  PARENT: [
    PERMISSIONS.APPLICATIONS_CREATE,
    PERMISSIONS.APPLICATIONS_READ_OWN,
    PERMISSIONS.CHILD_PRIVATE_READ,
    PERMISSIONS.EVENTS_READ_PUBLIC,
    PERMISSIONS.CONSENTS_MANAGE_OWN,
  ],
};

export const PLATFORM_PERMISSIONS: Record<PlatformRole, Permission[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
};
